# Generated by Django 5.2.16 on 2026-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date')),
                ('module', models.CharField(db_index=True, default='core', max_length=50, verbose_name='module')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur')], default='INFO', max_length=10, verbose_name='niveau')),
                ('message', models.TextField(verbose_name='message')),
            ],
            options={
                'verbose_name': 'entrée de journal',
                'verbose_name_plural': 'journal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, default='core', max_length=50, verbose_name='module')),
                ('key', models.CharField(max_length=100, verbose_name='clé')),
                ('value', models.TextField(blank=True, default='', verbose_name='valeur')),
                ('secret', models.BooleanField(default=False, verbose_name='valeur sensible')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'réglage',
                'verbose_name_plural': 'configuration',
                'constraints': [models.UniqueConstraint(fields=('module', 'key'), name='unique_setting_module_key')],
            },
        ),
    ]
