# Generated by Django 5.2.16 on 2026-07-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUTTON', 'Bouton poussoir'), ('SWITCH', 'Switch')], max_length=10, verbose_name='type')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='icône')),
                ('is_on', models.BooleanField(default=False, verbose_name='état')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'contrôle',
                'verbose_name_plural': 'contrôles',
                'ordering': ['created_at'],
            },
        ),
    ]
