# Generated by Django 5.2.16 on 2026-07-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('label', models.CharField(max_length=100, verbose_name='onglet')),
                ('icon', models.CharField(blank=True, default='puzzle', max_length=50, verbose_name='icône')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('enabled', models.BooleanField(default=False, verbose_name='activé')),
                ('installed_at', models.DateTimeField(auto_now_add=True, verbose_name='installé le')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['name'],
            },
        ),
    ]
