# Generated by Django 5.2.16 on 2026-07-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('enabled', models.BooleanField(default=True, verbose_name='activé')),
                ('definition', models.JSONField(default=dict, verbose_name='définition')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='dernière exécution')),
                ('last_status', models.CharField(blank=True, default='', max_length=200, verbose_name='dernier statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'scénario',
                'verbose_name_plural': 'scénarios',
                'ordering': ['name'],
            },
        ),
    ]
