# Generated by Django 5.2.16 on 2026-07-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('value', models.CharField(blank=True, default='', max_length=200, verbose_name='valeur')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='description')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
            ],
            options={
                'verbose_name': 'variable',
                'verbose_name_plural': 'variables',
                'ordering': ['name'],
            },
        ),
    ]
