# Generated by Django 5.2.16 on 2026-07-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='group',
            field=models.CharField(blank=True, default='', help_text='Switchs du même groupe : un seul peut être ON à la fois.', max_length=50, verbose_name='groupe exclusif'),
        ),
    ]
