# Generated by Django 5.2.16 on 2026-07-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_control_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='bloc')),
                ('order', models.IntegerField(default=0, verbose_name='ordre')),
                ('width', models.IntegerField(choices=[(4, 'Un tiers'), (6, 'Moitié'), (8, 'Deux tiers'), (12, 'Pleine largeur')], default=6, verbose_name='largeur')),
            ],
            options={
                'verbose_name': 'bloc du tableau de bord',
                'verbose_name_plural': 'blocs du tableau de bord',
                'ordering': ['order', 'id'],
            },
        ),
    ]
